<!-- Vendor Scripts -->
<script src="{{ asset('assets/js/vendor.min.js') }}"></script>
<!-- Plugin's Scripts -->
<script src="{{ asset('assets/plugins/fancybox/jquery.fancybox.min.js') }}"></script>
<script src="{{ asset('assets/plugins/nice-select/jquery.nice-select.min.js') }}"></script>
<script src="{{ asset('assets/plugins/aos/aos.min.js') }}"></script>
<script src="{{ asset('assets/plugins/slick/slick.min.js') }}"></script>
<script src="{{ asset('assets/plugins/waypoints.min.js') }}"></script>
<script src="{{ asset('assets/plugins/counter-up/jquery.counterup.min.js') }}"></script>
<script src="{{ asset('assets/plugins/isotope/isotope.pkgd.min.js') }}"></script>
<script src="{{ asset('assets/plugins/isotope/packery.pkgd.min.js') }}"></script>
<script src="{{ asset('assets/plugins/isotope/image.loaded.js') }}"></script>
<script src="{{ asset('assets/plugins/menu/menu.js') }}"></script>
<script src="{{ asset('assets/plugins/swiper/swiper-bundle.min.js') }}"></script>
<script src="{{ asset('assets/plugins/swiper/swiper.js') }}"></script>
<!-- Activation Script -->
<script src="{{ asset('assets/js/custom.js') }}"></script>
